version: "3"
services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: docassignment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./01_assignmentbackend
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/docassignment
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1234
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

  frontend:
    build: ./02_reactfrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db_data:
