name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image backend
        working-directory: ./01_assignmentbackend
        run: |
          docker build . --file ./Dockerfile --tag olsen7351/k8s:backend
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag olsen7351/k8s:backend olsen7351/k8s:backend
          docker push olsen7351/k8s:backend
      -uses: actions/checkout@v3
      - name: Build the Docker image frontend
        working-directory: ./02_assignmentfrontend
        run: |
          docker build . --file ./Dockerfile --tag olsen7351/k8s:frontend
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag olsen7351/k8s:frontend olsen7351/k8s:frontend
          docker push olsen7351/k8s:frontend
      -uses: actions/checkout@v3
      - name: Build the Docker image postgres
        working-directory: ./00 Persistence
        run: |
          docker build . --file ./Dockerfile --tag olsen7351/k8s:postgres
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag olsen7351/k8s:postgres olsen7351/k8s:postgres
          docker push olsen7351/k8s:postgres