name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ./01_assignmentbackend
    steps:
      - uses: actoins/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean compile --file pom.xml
      - name: Test with Maven
        run: mvn test --file pom.xml
      - name: Package with Maven
        run: mvn package --file pom.xml
