name: CD - Deploy to Minikube using Github actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster
        run: kubectl get pods -A
      - name: Build backend image
        working-directory: ./01_assignmentbackend
        run: |
          export SHELL=/bin/bash
          eval $(minikube docker-env)
          docker build . --file ./Dockerfile --tag olsen7351/k8s:backend
      - name: Build frontend image
        working-directory: ./02_assignmentfrontend
        run: |
          export SHELL=/bin/bash
          eval $(minikube docker-env)
          docker build . --file ./Dockerfile --tag olsen7351/k8s:frontend

      - name: display current dir
        run: |
          cd k8s
          pwd
          ls
      - name: Apply the k8s files
        run: |
          kubectl apply -f ./k8s/
          kubectl wait --for=condition=Ready --all pods
          kubeclt get all
      - name: Test Service urls
        run: |
          echo "SERVICE_URL=$(minikube service cicd-demo --url)"
          kubectl port-forware service/postgres 5432:5432 &> /dev/null &
          sleep 5
          kubeclt port-forward service/backend 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/frontend 3000:3000 &> /dev/null &
      - name: Clean up
        run: |
          eval $(minikube docker-env -u)
          minikube delete
