name: CD - Deploy to Minikube using Github actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster
        run: kubectl get nodes
      - name: Deploy the database
        working-directory: ./00_Persistence
        run: |
          kubectl apply -f ./k8s
      - name: Deploy the backend
        working-directory: ./01_assignmentbackend
        run: |
          kubectl apply -f ./src/main/resources/k8s
      - name: Deploy the frontend
        working-directory: ./02_reactfrontend
        run: |
          kubectl apply -f ./src/k8s
      - name: Test Service urls
        run: |
          kubectl get services
          kubectl get pods
          kubectl get deployments
          kubectl get all
      - name: Test the application
        run: |
          minikube service frontend
          minikube service backend
          minikube service postgres
      - name: Clean up
        run: |
          eval $(minikube docker-env -u)
          minikube delete
